{{ 
    config(
        materialized='incremental',
        incremental_strategy='append',
        tags=['ecopay', 'staging', 'transations']
    ) 
}}

SELECT
    -- Extract all keys in data field
    {{ extract_json('data', '__v', 'INT') }} as __v,
    {{ extract_json('data', '_id.$oid') }} as id,
    {{ extract_json('data', '_ver', 'NUMERIC(15,2)') }} as _ver,
    {{ extract_json('data', 'amount', 'NUMERIC(15,2)') }} as amount,
    {{ extract_json('data', 'app_url') }} as app_url,
    {{ extract_json('data', 'approval_code') }} as approval_code,
    {{ extract_json('data', 'auto_paid', 'BOOL') }} as auto_paid,
    {{ extract_json('data', 'auto_reconcile_dest_acc_info', 'JSONB') }} as auto_reconcile_dest_acc_info,
    {{ extract_json('data', 'bank_code') }} as bank_code,
    {{ extract_json('data', 'bank_payment_url') }} as bank_payment_url,
    {{ extract_json('data', 'bank_terminal_id') }} as bank_terminal_id,
    {{ extract_json('data', 'bank_type') }} as bank_type,
    {{ extract_json('data', 'bill_info', 'JSONB') }} as bill_info,
    {{ extract_json('data', 'billpay_data', 'JSONB') }} as billpay_data,
    {{ extract_json('data', 'business_entity_id') }} as business_entity_id,
    {{ extract_json('data', 'card_info', 'JSONB') }} as card_info,
    {{ extract_json('data', 'card_input_retries', 'NUMERIC(15,2)') }} as card_input_retries,
    {{ extract_json('data', 'cashback_amt', 'NUMERIC(15,2)') }} as cashback_amt,
    {{ extract_json('data', 'cashback_request_amt', 'NUMERIC(15,2)') }} as cashback_request_amt,
    {{ extract_json('data', 'create_payment_token', 'BOOL') }} as create_payment_token,
    {{ extract_json_timestamp_no_timezone('data', 'created_at') }} as created_at,
    {{ extract_json('data', 'created_by') }} as created_by,
    {{ extract_json('data', 'currency') }} as currency,
    {{ extract_json('data', 'customer_account') }} as customer_account,
    {{ extract_json('data', 'customer_address') }} as customer_address,
    {{ extract_json('data', 'customer_email') }} as customer_email,
    {{ extract_json('data', 'customer_mobile_number') }} as customer_mobile_number,
    {{ extract_json('data', 'customer_name') }} as customer_name,
    {{ extract_json('data', 'description') }} as description,
    {{ extract_json('data', 'destination_account') }} as destination_account,
    {{ extract_json('data', 'ecopay_extra_data') }} as ecopay_extra_data,
    {{ extract_json('data', 'extra_data', 'JSONB') }} as extra_data,
    {{ extract_json('data', 'exchange_currencies', 'JSONB') }} as exchange_currencies,
    {{ extract_json('data', 'expires_date') }} as expires_date,   
    {{ extract_json('data', 'fv_payment_transid') }} as fv_payment_transid,
    {{ extract_json('data', 'generator_partner_code') }} as generator_partner_code,
    {{ extract_json('data', 'initial_amount', 'NUMERIC(15,2)') }} as initial_amount,
    {{ extract_json('data', 'installment_info', 'JSONB') }} as installment_info,
    {{ extract_json('data', 'ipn_url') }} as ipn_url,
    {{ extract_json('data', 'is_forced_manually_reconcile', 'BOOL') }} as is_forced_manually_reconcile,
    {{ extract_json('data', 'is_keep_input', 'BOOL') }} as is_keep_input,
    {{ extract_json('data', 'is_partner_processing', 'BOOL') }} as is_partner_processing,
    {{ extract_json('data', 'is_reconciled', 'BOOL') }} as is_reconciled,
    {{ extract_json('data', 'is_refund', 'BOOL') }} as is_refund,
    {{ extract_json('data', 'is_send_otp', 'BOOL') }} as is_send_otp,
    {{ extract_json('data', 'match_bank_info', 'JSONB') }} as match_bank_info,
    {{ extract_json('data', 'mcc_group') }} as mcc_group,
    {{ extract_json('data', 'mcc_group_snapshot', 'JSONB') }} as mcc_group_snapshot,
    {{ extract_json('data', 'merchant_app_url') }} as merchant_app_url,
    {{ extract_json('data', 'merchant_code') }} as merchant_code,
    {{ extract_json('data', 'merchant_name') }} as merchant_name,
    {{ extract_json('data', 'merchant_user_id') }} as merchant_user_id,
    {{ extract_json('data', 'order_id') }} as order_id,
    {{ extract_json('data', 'original_amount', 'NUMERIC(15,2)') }} as original_amount,
    {{ extract_json('data', 'otp_transid') }} as otp_transid,
    {{ extract_json_timestamp_no_timezone('data', 'paid_at') }} as paid_at,
    {{ extract_json('data', 'parent_merchant_code') }} as parent_merchant_code,
    {{ extract_json('data', 'partmer_transid_old') }} as partmer_transid_old,
    {{ extract_json('data', 'partner_code') }} as partner_code,
    {{ extract_json_timestamp_no_timezone('data', 'partner_payment_at') }} as partner_payment_at,
    {{ extract_json('data', 'partner_profile') }} as partner_profile,
    {{ extract_json('data', 'partner_profile_snapshot', 'JSONB') }} as partner_profile_snapshot,
    {{ extract_json('data', 'partner_transid') }} as partner_transid,
    {{ extract_json('data', 'partner_transid_old') }} as partner_transid_old,
    {{ extract_json('data', 'paylater_info', 'JSONB') }} as paylater_info,
    {{ extract_json('data', 'payment_channel') }} as payment_channel,
    {{ extract_json('data', 'payment_link_reqid') }} as payment_link_reqid,
    {{ extract_json('data', 'payment_link_transid') }} as payment_link_transid,
    {{ extract_json('data', 'payment_service') }} as payment_service,
    {{ extract_json('data', 'payment_source') }} as payment_source,
    {{ extract_json('data', 'payment_url') }} as payment_url,
    {{ extract_json('data', 'platform') }} as platform,
    {{ extract_json('data', 'pos_transaction') }} as pos_transaction,
    {{ extract_json('data', 'prev_status') }} as prev_status,
    {{ extract_json_timestamp_no_timezone('data', 'processing_at') }} as processing_at,
    {{ extract_json('data', 'provider_code') }} as provider_code,
    {{ extract_json('data', 'purpose_of_transaction') }} as purpose_of_transaction,
    {{ extract_json('data', 'qrcode') }} as qrcode,
    {{ extract_json('data', 'qrcode_mapping_code') }} as qrcode_mapping_code,
    {{ extract_json('data', 'qrcode_payment_type') }} as qrcode_payment_type,
    {{ extract_json('data', 'reason') }} as reason,
    {{ extract_json('data', 'reconcile_acc', 'JSONB') }} as reconcile_acc,
    {{ extract_json('data', 'reconcile_account', 'JSONB') }} as reconcile_account,
    {{ extract_json('data', 'reconcile_data', 'JSONB') }} as reconcile_data,
    {{ extract_json('data', 'reconcile_dest_acc_info', 'JSONB') }} as reconcile_dest_acc_info,
    {{ extract_json('data', 'reconcile_list', 'JSONB') }} as reconcile_list,
    {{ extract_json('data', 'redirect_url') }} as redirect_url,
    {{ extract_json('data', 'refund_transid_list', 'JSONB') }} as refund_transid_list,
    {{ extract_json('data', 'refunded_amt', 'NUMERIC(15,2)') }} as refunded_amt,
    {{ extract_json('data', 'refunded_request_amt', 'NUMERIC(15,2)') }} as refunded_request_amt,
    {{ extract_json('data', 'req_eco_transfer_id') }} as req_eco_transfer_id,
    {{ extract_json('data', 'req_eco_transfer_to_merchant_id') }} as req_eco_transfer_to_merchant_id,
    {{ extract_json_timestamp_no_timezone('data', 'req_time') }} as req_time,
    {{ extract_json_timestamp_no_timezone('data', 'request_create_at') }} as request_create_at,
    {{ extract_json('data', 'request_create_from') }} as request_create_from,
    {{ extract_json('data', 'res_eco_transfer_id') }} as res_eco_transfer_id,
    {{ extract_json('data', 'res_eco_transfer_to_merchant_id') }} as res_eco_transfer_to_merchant_id,
    {{ extract_json('data', 'result_code') }} as result_code,
    {{ extract_json('data', 'service_type') }} as service_type,
    {{ extract_json('data', 'source_account') }} as source_account,
    {{ extract_json('data', 'source_issuer') }} as source_issuer,
    {{ extract_json('data', 'status') }} as status,
    {{ extract_json('data', 'status_user_fee', 'BOOL') }} as status_user_fee,
    {{ extract_json('data', 'step', 'JSONB') }} as step,
    {{ extract_json('data', 'steps', 'JSONB') }} as steps,
    {{ extract_json('data', 'store_code') }} as store_code,
    {{ extract_json('data', 'store_label') }} as store_label,
    {{ extract_json('data', 'sub_bank_type') }} as sub_bank_type,
    {{ extract_json('data', 'sub_payment_channel') }} as sub_payment_channel,
    {{ extract_json_timestamp_no_timezone('data', 'synched_at') }} as synched_at,
    {{ extract_json('data', 'terminal_code') }} as terminal_code,
    {{ extract_json('data', 'terminal_id') }} as terminal_id,
    {{ extract_json('data', 'terminal_label') }} as terminal_label,
    {{ extract_json('data', 'tokenization.$oid') }} as tokenization,
    {{ extract_json('data', 'total_cashback_fee', 'NUMERIC(15,2)') }} as total_cashback_fee,
    {{ extract_json('data', 'total_fee', 'DOUBLE PRECISION') }} as total_fee,
    {{ extract_json('data', 'total_refund_fee', 'NUMERIC(15,2)') }} as total_refund_fee,
    {{ extract_json('data', 'total_user_fee', 'NUMERIC(15,2)') }} as total_user_fee,
    {{ extract_json('data', 'transaction_fee_snapshot', 'JSONB') }} as transaction_fee_snapshot,
    {{ extract_json('data', 'transid') }} as transid,
    {{ extract_json_timestamp_no_timezone('data', 'updatedAt') }} as updatedAt,
    {{ extract_json_timestamp_no_timezone('data', 'updated_at') }} as updated_at,
    {{ extract_json('data', 'updated_by') }} as updated_by,
    {{ extract_json('data', 'manager_team_id.$oid') }} as manager_team_id,
    {{ extract_json_timestamp_no_timezone('data', 'settlement_at') }} as settlement_at,
    {{ extract_json('data', 'user_fee', 'NUMERIC(15,2)') }} as user_fee,
    {{ extract_json('data', 'user_fee_snapshot', 'JSONB') }} as user_fee_snapshot,
    -- Get others fields
    op,
    ts_ms,
    inserted_at as json_inserted_at,
    CURRENT_TIMESTAMP() inserted_at
FROM {{ source('json_raw', 'ecopay_ecopay_transactions') }}
{% if is_incremental() %}
WHERE inserted_at > (SELECT COALESCE(MAX(json_inserted_at), TIMESTAMP '1970-01-01 00:00:00') FROM {{ this }})
{% endif %}
{% if target.name == 'dev' %}
LIMIT 100000
{% endif %}