{{
    config(
        materialized='incremental',
        incremental_strategy='append',
        tags=['dms', 'dms-v1', 'staging', 'users']
    )
}}

SELECT
    -- Extract all keys in data field
    {{ extract_json('data', '__v', 'INT') }} as __v,
    {{ extract_json('data', '_id.$oid') }} as id,
    {{ extract_json('data', 'account_id') }} as account_id,
    {{ extract_json('data', 'area_group') }} as area_group,
    {{ extract_json('data', 'area_group_info', 'JSONB') }} as area_group_info,
    {{ extract_json('data', 'area_groups', 'JSONB') }} as area_groups,
    {{ extract_json('data', 'area_groups_info', 'JSONB') }} as area_groups_info,
    {{ extract_json('data', 'avatar') }} as avatar,
    {{ extract_json_timestamp_no_timezone('data', 'birthday.$date') }} as birthday,
    {{ extract_json('data', 'code') }} as code,
    {{ extract_json('data', 'company.$oid') }} as company_id,
    {{ extract_json('data', 'company_info', 'JSONB') }} as company_info,
    {{ extract_json_timestamp_no_timezone('data', 'created_at.$date') }} as created_at,
    {{ extract_json('data', 'created_by') }} as created_by,
    {{ extract_json('data', 'created_by_area_group.$oid') }} as created_by_area_group,
    {{ extract_json('data', 'created_by_group.$oid') }} as created_by_group,
    {{ extract_json('data', 'created_by_user.$oid') }} as created_by_user,
    {{ extract_json('data', 'created_by_user_info', 'JSONB') }} as created_by_user_info,
    {{ extract_json('data', 'default_distributor') }} as default_distributor,
    {{ extract_json('data', 'default_distributor_info', 'JSONB') }} as default_distributor_info,
    {{ extract_json('data', 'device_id') }} as device_id,
    {{ extract_json('data', 'direct_manager.$oid') }} as direct_manager,
    {{ extract_json('data', 'direct_manager_info', 'JSONB') }} as direct_manager_info,
    {{ extract_json('data', 'distributor.$oid') }} as distributor_id,
    {{ extract_json('data', 'distributor_info', 'JSONB') }} as distributor_info,
    {{ extract_json('data', 'distributors', 'JSONB') }} as distributors,
    {{ extract_json('data', 'distributors_info', 'JSONB') }} as distributors_info,
    {{ extract_json_timestamp_no_timezone('data', 'end_date.$date') }} as end_date,
    {{ extract_json('data', 'email') }} as email,
    {{ extract_json('data', 'friends', 'JSONB') }} as friends,
    {{ extract_json('data', 'group.$oid') }} as group_id,
    {{ extract_json('data', 'group_chats', 'JSONB') }} as group_chats,
    {{ extract_json('data', 'group_info', 'JSONB') }} as group_info,
    {{ extract_json('data', 'groups', 'JSONB') }} as groups,
    {{ extract_json('data', 'groups_info', 'JSONB') }} as groups_info,
    {{ extract_json('data', 'histories_role_changed', 'JSONB') }} as histories_role_changed,
    {{ extract_json('data', 'history_resource') }} as history_resource,
    {{ extract_json('data', 'is_calculation_salary', 'BOOL') }} as is_calculation_salary,
    {{ extract_json('data', 'is_not_save_info', 'BOOL') }} as is_not_save_info,
    {{ extract_json('data', 'is_synchronized', 'BOOL') }} as is_synchronized,
    {{ extract_json('data', 'keycloak_id') }} as keycloak_id,
    {{ extract_json('data', 'kpi_target') }} as kpi_target,
    {{ extract_json('data', 'kpi_targets', 'JSONB') }} as kpi_targets,
    {{ extract_json('data', 'kpi_targets_info') }} as kpi_targets_info,
    {{ extract_json_timestamp_no_timezone('data', 'last_sync_at.$date') }} as last_sync_at,
    {{ extract_json('data', 'location', 'JSONB') }} as `location`,
    {{ extract_json('data', 'name') }} as name,
    {{ extract_json('data', 'new_area_group.$oid') }} as new_area_group,
    {{ extract_json('data', 'new_area_group_info', 'JSONB') }} as new_area_group_info,
    {{ extract_json('data', 'new_area_groups', 'JSONB') }} as new_area_groups,
    {{ extract_json('data', 'new_area_groups_info', 'JSONB') }} as new_area_groups_info,
    {{ extract_json('data', 'new_location', 'JSONB') }} as new_location,
    {{ extract_json('data', 'new_rsd_area_group.$oid') }} as new_rsd_area_group,
    {{ extract_json('data', 'new_rsd_area_group_info', 'JSONB') }} as new_rsd_area_group_info,
    {{ extract_json('data', 'new_rsm_area_group.$oid') }} as new_rsm_area_group,
    {{ extract_json('data', 'new_rsm_area_group_info', 'JSONB') }} as new_rsm_area_group_info,
    {{ extract_json('data', 'notify', 'JSONB') }} as notify,
    {{ extract_json('data', 'password') }} as `password`,
    {{ extract_json('data', 'phone') }} as phone,
    {{ extract_json('data', 'phone_contact') }} as phone_contact,
    {{ extract_json('data', 'reference', 'JSONB') }} as reference,
    {{ extract_json('data', 'role_groups', 'JSONB') }} as role_groups,
    {{ extract_json('data', 'role_groups_info', 'JSONB') }} as role_groups_info,
    {{ extract_json('data', 'roles', 'JSONB') }} as roles,
    {{ extract_json('data', 'roles_info', 'JSONB') }} as roles_info,
    {{ extract_json('data', 'route.$oid') }} as `route`,
    {{ extract_json('data', 'route_info', 'JSONB') }} as route_info,
    {{ extract_json('data', 'routes', 'JSONB') }} as routes,
    {{ extract_json('data', 'routes_future', 'JSONB') }} as routes_future,
    {{ extract_json('data', 'routes_future_info', 'JSONB') }} as routes_future_info,
    {{ extract_json('data', 'routes_info', 'JSONB') }} as routes_info,
    {{ extract_json('data', 'rsd_area_group.$oid') }} as rsd_area_group,
    {{ extract_json('data', 'rsd_area_group_info', 'JSONB') }} as rsd_area_group_info,
    {{ extract_json('data', 'rsm_area_group.$oid') }} as rsm_area_group,
    {{ extract_json('data', 'rsm_area_group_info', 'JSONB') }} as rsm_area_group_info,
    {{ extract_json('data', 'sex') }} as sex,
    {{ extract_json('data', 'sso_code') }} as sso_code,
    {{ extract_json('data', 'sso_id') }} as sso_id,
    {{ extract_json('data', 'sso_roles', 'JSONB') }} as sso_roles,
    {{ extract_json_timestamp_no_timezone('data', 'start_date.$date') }} as start_date,
    {{ extract_json('data', 'status') }} as status,
    {{ extract_json_timestamp_no_timezone('data', 'synchronized_at.$date') }} as synchronized_at,
    {{ extract_json('data', 'third_party_user_code') }} as third_party_user_code,
    {{ extract_json('data', 'title') }} as title,
    {{ extract_json_timestamp_no_timezone('data', 'updated_at.$date') }} as updated_at,
    {{ extract_json('data', 'updated_by') }} as updated_by,
    {{ extract_json('data', 'updated_by_user.$oid') }} as updated_by_user,
    {{ extract_json('data', 'updated_by_user_info', 'JSONB') }} as updated_by_user_info,
    {{ extract_json('data', 'user.$oid') }} as user,
    {{ extract_json('data', 'user_info', 'JSONB') }} as user_info,
    -- Get others fields
    op,
    ts_ms,
    inserted_at as json_inserted_at,
    CURRENT_TIMESTAMP() as inserted_at
FROM {{ source('json_raw', 'dms1_users') }}
{% if is_incremental() %}
WHERE inserted_at > (SELECT COALESCE(MAX(json_inserted_at), TIMESTAMP '1970-01-01 00:00:00') FROM {{ this }})
{% endif %}
